# This file provides instructions for packaging.

`MooseX-DeclareX-plugin-abstract`
	perl_version_from m`MooseX::DeclareX::plugin::abstract`;
	version_from      m`MooseX::DeclareX::plugin::abstract`;
	readme_from       m`MooseX::DeclareX::plugin::abstract`;
	test_requires     p`Test::More 0.61`  .

